AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  functional-scala-lambda

  Sample SAM Template for functional-scala-lambda

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  FunctionalScalaLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        - DynamoDBReadPolicy:
                      TableName: users
    Metadata:
      DockerTag: java8.al2-maven-v1
      DockerContext: ./FunctionalScalaLambda
      Dockerfile: Dockerfile
